### ISSUE TITLE
Instrument question

### ISSUE THREAD

**Issue by Engelberg** [jeaye/orchestra#1]
Does instrument with no args instrument everything in the given namespace, or everything across all namespaces?

**Comment by jeaye** [comment]
It instruments all spec'd functions in the `clojure.spec/registry`, just like `clojure.spec.test/instrument`. To help you know what's being checked, the `instrument` function returns a collection of all syms naming the vars which have been instrumented.

**Comment by jeaye** [comment]
I should've been even more clear, I think: this will instrument all functions, across all required namespaces, which provide an `fspec`.

**Comment by Engelberg** [comment]
Thank you for the clarification.
