### ISSUE TITLE
Strange issue found

### ISSUE THREAD

**Issue by kingfranz** [jeaye/orchestra#15]
Hi,
Love the lib but I've found something strange.

The function get-lists-with-count returns :shop/lists-with-count.
If I change list-tbl to a "normal" function with :pre everything is fine, but as shown here it complains that the call to list-tbl did not conform.

```
clojure.lang.ExceptionInfo: Call to #'shop2.views.home/list-tbl did not conform to spec:
In: [0] val: ({:_id "d3fcd54e-92bf-41c1-b2ad-69a619eaa9ba", :entryname "Coop", :parent {:_id "61c53379-b686-4681-a8f3-5b14e86a0827", :entryname "Mat", :parent nil}, :last false, :count 0, :total 0} 
...
fails spec: :shop/list-with-count at: [:args :lists] predicate: map?

```
Notice that it says :shop/list-with-count instead of :shop/lists-with-count

```
(s/def :shop/list-with-count (s/keys :req-un [:shop/_id :shop/entryname :list/parent :list/last :list/count :list/total]))
(s/def :shop/lists-with-count (s/* :shop/list-with-count))

(defn-spec list-tbl any?
    [lists :shop/lists-with-count lists]
    [:table.width-100p
     (for [a-list (sort-by identity list-cmp lists)]
         [:tr [:td (list-row a-list)]])])

(defn-spec list-tree any?
           [request map?]
           (let [lists (get-lists-with-count)]
               (if (want-tree? request)
                   [:ul.tree
             (map #(sub-tree lists %)
                  (->> lists
                       (filter #(nil? (:parent %)))
                       (sort-by :entryname)))]
                   (list-tbl lists))))

```

Regards
Sören Svensson

**Comment by kingfranz** [comment]
I found out that it works with s/coll-of but not with s/*

**Comment by jeaye** [comment]
Hey @kingfranz, thanks for reporting in and I'm glad you're liking Orchestra. My understanding is that this is not an Orchestra issue, but is a misusage of `s/*`. As you found, `s/coll-of` is the right tool for the job.

I'll leave this open in case you have any more concerns.

**Comment by kingfranz** [comment]
Thanks. Apparently I don't know spec as well as I thought :-)
