### ISSUE TITLE
README out of date? defn-spec gone?

### ISSUE THREAD

**Issue by bkovitz** [jeaye/orchestra#19]
I'd like to try orchestra (it looks great!), but I'm running into some difficulties getting started.

The README says to include this dependency in Leiningen's .project file:
    [orchestra "0.2.0"]

Another dependency I've got in the .profile file is `[org.clojure/clojure "1.9.0"]`, so I think that should ensure that clojure.spec is available.

With this in my `ns`:
    (:require [orchestra.spec.test :as st :refer [defn-spec]]))

I got this error message:
    CompilerException java.io.FileNotFoundException: Could not locate clojure/spec__init.class or clojure/spec.clj on classpath., compiling:(orchestra/spec/test.clj:1:1) 

Looking around in the Issues here on github, I got the impression that orchestra's current version might be 0.3.0. I changed the Leiningen dependency to:
    [orchestra "0.3.0"]

Now, I get this error message when I try to execute the `ns` that requires orchestra:
    CompilerException java.lang.IllegalAccessError: defn-spec does not exist, compiling:(farg/x.clj:1:1) 

Am I doing something wrong? Maybe using the wrong version? Has `defn-spec` been changed to something else? Is the README just out of date?

**Comment by jeaye** [comment]
Hey, thanks for the issue. The README is entirely up to date, but it has mislead you. In this section: https://github.com/jeaye/orchestra#usage the newest version is shown as: `[orchestra "2017.11.12-1"]` which has the Clojure requirements of:

```clojure
;; Clojure requirements
;;    org.clojure/clojure >= 1.9.0-alpha16
;;    org.clojure/spec.alpha >= 0.1.108
;;
;; ClojureScript requirements
;;    org.clojure/clojurescript >= 1.9.671
```

Another helpful way to find this is with the badge at the top of the README, which is common among many Clojure repos (you can click on it): [![Clojars Project](https://img.shields.io/clojars/v/orchestra.svg)](https://clojars.org/orchestra)

Let me know if you hit any more issues!
