### ISSUE TITLE
Problem with varargs

### ISSUE THREAD

**Issue by divs1210** [jeaye/orchestra#20]
I have the following code:

```clojure
(s/def ::ingredient
  (s/cat
   :name string?
   :quantity number?
   :unit keyword?))


(s/def ::mixture
  (s/map-of string?
            (s/cat :quantity number?
                   :unit keyword?)))


(defn-spec mix ::mixture
  [& ingredients (s/coll-of ::ingredient)]
  (into {}
        (map (juxt first rest)
             ingredients)))
```

It works without instrumentation:
```clojure
(mix ["sugar" 2 :tbsp] ["water" 4 :cup])

;; => {"sugar" (2 :tbsp), "water" (4 :cup)}
```

But it doesn't seem to work as expected with instrumentation on:
```clojure
(st/instrument)

(mix ["sugar" 2 :tbsp] ["water" 4 :cup])

;; => clojure.lang.ExceptionInfo: Call to #'specd.core/mix did not conform to spec:
;; In: [0] val: ["sugar" 2 :tbsp] fails spec: :specd.core/ingredient at: [:args :& :name] predicate: string?
```

What am I doing wrong?

**Comment by madstap** [comment]
It's not obvious to me why, but changing `(s/coll-of ::ingredient)` to `(s/* (s/spec ::ingredient))` makes it work.

Which is really strange as these are both true:

```
(s/valid? (s/coll-of ::ingredient) '(["sugar" 2 :tbsp] ["water" 4 :cup]))

(s/valid? (s/* (s/spec ::ingredient)) '(["sugar" 2 :tbsp] ["water" 4 :cup]))
```

**Comment by jeaye** [comment]
Gah, been meaning to get to this, but I've `<excuse here>`. In short, you're quite right that this is an issue with your spec, not an issue with Orchestra. I've hit the same exact thing before, puzzled over it, got an explanation from Alex Miller, and ultimately boiled it down to this.

1. When you're using `& args` within a spec, use `s/*`. The pattern matching aspect of spec applies to different contexts than the typical data structure spec'ing, but someone else knows more about this than me.
