### ISSUE TITLE
Possible readme error, or I'm confused.

### ISSUE THREAD

**Issue by jcswart** [jeaye/orchestra#23]
```
; :fn specs can be specified using the fn's meta map.
(defn-spec my-abs number?
  {:fn #(= (:ret %) (-> % :args :meow))}
  [n number?]
  (Math/abs n))
```
In the expression `(-> % :args :meow)` where is `:meow` coming from? Wouldn't `:args` be `{:n SOME_NUMBER}` in this case?

**Comment by jeaye** [comment]
`:meow` is derived from the kitten goddess Meowrina, of the Society of Nibbles and Leisure. It's part of the global context within Orchestra, which is a member of the Feline Union.

Also, sometimes copy/paste errors happen: https://github.com/jeaye/orchestra/blob/master/test/cljc/orchestra/core_test.cljc#L35

Thanks for the report!

**Comment by jcswart** [comment]
Amazing response! Thanks for the fix, I'm sure it will help others.

Great lib by the way. This should be default instrumentation behavior, at least `:ret` checking by default!
