### ISSUE TITLE
Provide global flag for enabling instrumentation

### ISSUE THREAD

**Issue by JAremko** [jeaye/orchestra#24]
Can we have a global flag like [`*assert*`](https://clojuredocs.org/clojure.core/*assert*) but for enabling instrumentation instead? 

Sticking `instrument` in various places doesn't work great with code segment evaluation.

**Comment by jeaye** [comment]
`instrument` is a macro which needs to run, once all of the `s/fdef` calls have been made. This is a feature of clojure.spec, not Orchestra. Your best bet is to use `instrument` once, after requiring every ns you want to instrument.

**Comment by jeaye** [comment]
That is to say, without calling `instrument`, all of the `alter-var-root` calls (or `set!` calls in CLJS) won't run, which means the fns won't be instrumented. We could consider a flag to *disable* instrumentation, but that would need to be done in the instrumented shim itself, so `instrument` would still need to be called.

**Comment by JAremko** [comment]
Aha. Thanks  @jeaye  for responding so fast. 

> We could consider a flag to disable instrumentation

It's will be slightly better than doing something like:

```clojure
;; at the buffer end:
(when *assert* (st/instrument))
```
because I might want to decouple it from ` *assert*` and having standard flag always better + I'ts slightly less code.

**Comment by jeaye** [comment]
That can't work, since `instrument` is a macro and `*assert*` is a run-time value. We would need an environment variable or something else we can read at compile-time. The way my team handles it is to use [environ](https://github.com/weavejester/environ) within a macro to conditionally instrument. It looks like this:

```clojure
(when-not-prod ; This is a macro which checks an environment variable
    (let [instrumented (sort (stest/instrument))]
      (vprint :instrumenting instrumented)))
```

**Comment by JAremko** [comment]
@jeaye  Got it, thanks again :+1:

**Comment by jeaye** [comment]
Sure thing, @JAremko. Thanks for using Orchestra and suggesting the change!
