### ISSUE TITLE
:ret is not conformed into :fn

### ISSUE THREAD

**Issue by ezeaguerre** [jeaye/orchestra#26]
Hi! I have a spec'ed function, and it seems the return value is not conformed before passing it to the `:fn` spec.

### Description

Here's a contrived example:

```clojure
(ns example.example
  (:require [clojure.spec.alpha :as s]
            [clojure.spec.test.alpha :as st]
            [clojure.spec.gen.alpha :as gen]
            [orchestra.spec.test :as or]))

(defn do-something [string]
  (if (< (rand) 0.5)
    (str "your-" string)
    :error))

(s/fdef do-something
  :args (s/cat :string string?)
  :ret (s/or :error #{:error}
             :success string?)
  :fn #(condp = (-> % :ret key)
         :success (and (clojure.string/starts-with? (-> % :ret val) "your-")
                       (clojure.string/ends-with? (-> % :ret val) (-> % :args :string)))
         true))
```

When I perform a check:

```clojure
example.example> (st/check `do-something)
({:spec #object[clojure.spec.alpha$fspec_impl$reify__2451 0x3c2d27a4 "clojure.spec.alpha$fspec_impl$reify__2451@3c2d27a4"], :clojure.spec.test.check/ret {:result true, :num-tests 1000, :seed 1540250227537}, :sym example.example/do-something})
```
But when I instrument it with Orchestra:

```clojure
example.example> (or/instrument)
[example.example/do-something]
example.example> (do-something "issue")
ClassCastException java.lang.String cannot be cast to java.util.Map$Entry  clojure.core/key (core.clj:1559)
```

I can introduce a print statement in the `:fn` spec to show the difference between runs:

```clojure
example.example> (st/check  `do-something {:clojure.spec.test.check/opts {:num-tests 5}})

{:args {:string }, :ret [:error :error]}
{:args {:string }, :ret [:error :error]}
{:args {:string }, :ret [:success your-]}
{:args {:string 3}, :ret [:success your-3]}
{:args {:string }, :ret [:success your-]}
({:spec #object[clojure.spec.alpha$fspec_impl$reify__2451 0x73ec120e "clojure.spec.alpha$fspec_impl$reify__2451@73ec120e"], :clojure.spec.test.check/ret {:result true, :num-tests 5, :seed 1540250799398}, :sym example.example/do-something})
```
The return value of the function is conformed according to the spec, so the `:fn` spec receives either `[:error :error]` or `[:success "your-*"]`. However, when using Orchestra:

```clojure
example.example> (or/instrument)
[example.example/do-something]
example.example> (do-something "issue")
{:ret your-issue, :args {:string issue}}
ClassCastException java.lang.String cannot be cast to java.util.Map$Entry  clojure.core/key (core.clj:1559)
```

The arguments of the function are conformed appropriately, but the return value of the function is not. The `:fn` spec receives the plain string (or keyword) returned from the function.

### Lein project file

This is my lein project file:

```clojure
(defproject example "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/test.check "0.9.0"]
                 [orchestra "2018.09.10-1"]]
  :main ^:skip-aot example.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

### Summary

This is what gets passed to the `:fn` spec:

```clojure
{:args {:string "hi"} :ret "your-hi"}
```

This is what should be passed to it instead:

```clojure
{:args {:string "hi"} :ret [:success "your-hi"]}
```

**Comment by cjohansen** [comment]
I just hit this error as well, pairing [speculative-kaocha-plugin](https://github.com/borkdude/speculative-kaocha-plugin) with Orchestra. Any plans on resolving this?

**Comment by jeaye** [comment]
This is 100% an issue and I'd like also to see it resolved. It just hasn't been a blocked on my end, so it hasn't been prioritized. If either of you wants to make a PR with a fix (and ideally a test!), I'd be happy to take a look. Whatever we do, we'll need to do for CLJ and CLJS though. I'm not yet sure if this is also an issue in CLJS land, but it may be.

Thanks for the report and for the follow up. I want to be able to get to this, and some other Orchestra items, but the startup life is a crazy one, so it may be a bit.
