### ISSUE TITLE
Using `instrument` with clojurescript 1.10.439 generates warnings (nodejs compilation)

### ISSUE THREAD

**Issue by benzap** [jeaye/orchestra#31]
Hello,

I'm getting warnings when I use the `orchestra-cljs.spec.test/instrument` function. I'm also using it with figwheel, which by default won't load any code with warnings which has been causing a ton of issues.

The resulting output

```sh
Figwheel: Compile Warning - var: expound.alpha/specs is not public in file dev/server/cljs/user.cljs at line 151, column 1
Figwheel: Compile Warning - var: expound.alpha/value-in-context is not public in file dev/server/cljs/user.cljs at line 151, column 1
Figwheel: Not loading code with warnings - target/node/out-dev-server/cljs_deps.js
```

As a quickfix, you could make all of your functions public. I'm under the impression that the latest clojurescript is incorrectly analyzing certain functions when macro-expanding.

Thank you for your time,

Ben

**Comment by jeaye** [comment]
@benzap This is an Orchestra issue and has been fixed in master, but not yet released. I hope to get the release out this weekend. Thanks for the report!

**Comment by benzap** [comment]
Ah ok, thanks!

I just realized that is was an orchestra issue after I turned off expound. Glad to hear it will be fixed in the next release!
