### ISSUE TITLE
Have to re-instrument after every compile

### ISSUE THREAD

**Issue by Ritvik36** [jeaye/orchestra#47]
Hi I am relatively new to both clojure and programming.

I have noticed that after each time i recompile a namespace i have to call (orchestra/instrument) again, otherwise the specs aren't performed. 

For example  
`(defn add-this
  [x]
  (+ 2.0 x))`

`(clojure.spec.alpha/fdef add-this
:args (clojure.spec.alpha/cat :x integer?)
:ret integer?)`

when I call (orchestra/instrument) and run (add-this 3) it will fail on the :ret. But if i were to compile the namespace and run the same function it would not fail the :ret and would just return 5.0. In order to get the specs working again, I would need to run (orchestra/instrument) again in my repl.

I was wondering is this normal for spec and orchestra? If it is, is there any way to get around having to reinstrument each time?

I have tried to use mount.core (defstate instrument
  :start (ost/instrument)) which should rerun the state after each compile, but that doesn't seem to work either.

Thanks in advance!

**Comment by jeaye** [comment]
I don't think this is an Orchestra issue. Please verify the issue first doesn't happen with vanilla spec. If that's the case, we'll need to fix something here, but it shouldn't be. It's quite common, I've seen, to hook `(st/instrument)` into your hot reloading, for example, to ensure instrumentation is kept up to date with any changes. I'll leave this open until you verify.

**Comment by Ritvik36** [comment]
Hi there's no issue with orchestra or vanilla spec. Putting the instrument call at the bottom of the namespace fixed the issue.
