### ISSUE TITLE
Issue with native type hinting

### ISSUE THREAD

**Issue by l3nz** [jeaye/orchestra#48]
I came across an "interesting" bug with type hinting. I am interfacing to a Java library that expects a long value, so I thought I'd add a type hint to my instrumented method to avoid reflection.

```
(ns xxx
  (:require [clojure.spec.alpha :as s]
            [orchestra.spec.test :as orchestra]))

(defn typed-vals
  [^String s
   ^long n]
  (prn "String:" s "Number:" n))

(s/fdef
  typed-vals
  :args (s/cat :s string?
               :n int?))

(defn caller []
  (typed-vals "a" 1))

(orchestra/instrument)
```

Looks innocent enough, right? but it does not run, and fails with:

```
java.lang.ClassCastException: orchestra.spec.test$spec_checking_fn$fn__3173 cannot be cast to clojure.lang.IFn$OLO
	at xxx$caller.invokeStatic(xxx.clj:18)
	at xxx$caller.invoke(xxx.clj:18)
```

Interestingly, it works if I change it to:

```
(defn typed-vals
  [^String s
   ^Long n]
  (prn "String:" s "Number:" n))
```

My feeling is that the calling stub you create always generates a `fn(Object,Object):Object` for fn `typed-vals`, and for some reason this breaks if the called signature is  `fn(Object,long):Object`. Yes, one can use the Long wrapper and boxing/unboxing seems to happen natively, but this should at least  be documented somewhere? 

I am using `[orchestra "2019.02.06-1"]`.

BTW, native invocation interfaces are documented here: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/IFn.java

While I understand this is likely a corner  case, I think it  would be totally OK for Orchestra to fail explicitly when trying to instrument a method that contains primitive types,  but not when the  method is called.

**Comment by jeaye** [comment]
Hey @l3nz! Thanks for the report. I've looked into what's going on here and, unfortunately, it's nothing to do with Orchestra or `defn-spec`. This same issue will happen with vanilla clojure.spec.alpha instrumentation, which is what Orchestra uses behind the scenes.

The only thing Orchestra does is patches clojure.spec.alpha's instrumentation to also check return specs and `:fn` specs.

This can be verified by running the following (same code as yours, but no Orchestra):

```clojure
(ns xxx
  (:require [clojure.spec.alpha :as s]
            [clojure.spec.test.alpha :as st]))

(defn typed-vals
  [^String s
   ^long n]
  (prn "String:" s "Number:" n))

(s/fdef
  typed-vals
  :args (s/cat :s string?
               :n int?))

(defn caller []
  (typed-vals "a" 1))

(st/instrument)

(caller)
```

I'm closing this, but feel free to let me know if you have any other questions or concerns.

**Comment by l3nz** [comment]
You are  right.  It's https://clojure.atlassian.net/browse/CLJ-1941 and it's been there  for a while....
Do you think it would make sense to add a note on the README, so somebody else won't be bitten?
