### ISSUE TITLE
After patching implementation, multi-arity functions that have a spec/fdef breaks

### ISSUE THREAD

**Issue by raymond-w-ko** [jeaye/orchestra#53]
I encountered the real life use case and described it here: https://github.com/bhb/expound/issues/197
The minimal reproduction case is here: https://github.com/raymond-w-ko/spec-arity-repro
Run it by:
```
> npm install
> make watch
> # switch to another terminal
> node
>> const m = require("./handler"); m.handler();
```

Error:
```
Uncaught:
TypeError: playbox.fake_expound_str.cljs$core$IFn$_invoke$arity$2 is not a function
    at Object.playbox$handler (/home/rko/src/spec-arity-repro/cljs-runtime/playbox.cljs:29:3)
at Object.playbox$test_fn [as test_fn] (/home/rko/src/spec-arity-repro/cljs-runtime/playbox.cljs:25:3)
```

**Comment by raymond-w-ko** [comment]
I edited the repro case and title to make sure that breakage is not caused by using native `cljs.spec.test.alpha/instrument` vs `orchestra-cljs.spec.test/instrument`.

**Comment by jeaye** [comment]
Hey! Thanks for reporting this and for looking into it so much. I'm not sure what's up, off the top of my head; my company is indeed using `defn-spec` for multi-arity functions within CLJS, so I'm surprised we haven't yet seen this. It does warrant some investigation, though.

As you said, Orchestra recently moved from a fork to a monkey patch solution. My guess is similar to yours: we must just be missing something. Perhaps an interesting start would be to rule out shadow-cljs and the CLJS version you're on.

As I mentioned, I'm using the latest Orchestra with CLJS and have not seen this. The setup we have looks like this:

* Leiningen
* `[org.clojure/clojurescript "1.10.597"]`
* `[orchestra "2020.07.12-1"]`
* `[lein-cljsbuild "1.1.8"]`

I'm not familiar with using shadow-cljs + deps.edn; which CLJS version are you using?

**Comment by raymond-w-ko** [comment]
Oops, I left that out in `deps.edn`. I am using: `org.clojure/clojurescript {:mvn/version "1.10.773"}`

I tested an older version, `orchestra {:mvn/version "2019.02.06-1"}`, before the new implementation and can confirm it does work.
