### ISSUE TITLE
Orchestra does not work in ClojureScript

### ISSUE THREAD

**Issue by kelvinqian00** [jeaye/orchestra#57]
## Description

I am unable to bring in Orchestra as dependency in a cljs namespace.

## How to reproduce

Create a new `.cljs` or `.cljc` file, then in that file evaluate the following:

```clojure
(ns foo.bar.my-namespace
  (:require [orchestra.spec.test])
```
or
```clojure
(require '[orchestra.spec.test])
```

When evaluating, you should see an error message akin to the following:
```
; Unexpected error (ExceptionInfo) compiling at (test.cljc:19:43).
; Unable to resolve var: stacktrace-relevant-to-instrument in this context at line 19 file:/Users/username/.m2/repository/orchestra/orchestra/2021.01.01-1/orchestra-2021.01.01-1.jar!/orchestra/spec/test.cljc
```

Note: This will _only_ happen in ClojureScript; it works perfectly fine in Clojure.

## Version Details

These are the version details from my `deps.edn` file.
- Orchestra: 2021.01.01-1
- ClojureScript: 1.10.764 (though it is reproducible on the latest 1.10.896 version also)
- clojure/test.check: 1.1.0
- olical/cljs-test-runner: 3.8.0

This occurs both on my MacBook (macOS Big Sur v11.6) and during GitHub CI (which uses Ubuntu 20.04.3 LTS).

**Comment by jeaye** [comment]
Please double check the readme. :) You're not using the correct namespace for cljs.

```clojure
(ns kitty-ninja
  (:require [orchestra.core :refer-macros [defn-spec]]
            [orchestra-cljs.spec.test :as st]
            [clojure.spec.alpha :as s]))
```

More info on why that's needed is here: https://blog.jeaye.com/2017/06/30/orchestra-cljs/

Kind regards,
Jeaye

**Comment by kelvinqian00** [comment]
D'oh! My mistake! That said, I think it would be very helpful to include an explicit _"**Note:** ..."_ passage in the README, since this is the first time I'd have to call completely different namespaces for the same library, so it wasn't obvious to me when I was quickly bringing in the library as a dep.

**Comment by Quezion** [comment]
Leaving a git-searchable note for dummies running into this error like myself (I was converting from a .cljc file & missed the doc)

On the modern version of Orchestra, you'll probably get an error saying "distinct-by missing from cljs.core." That means you need to fix your namespaces like above ^^
