### ISSUE TITLE
Spec or return value not evaluated when throwing error

### ISSUE THREAD

**Issue by vikeri** [jeaye/orchestra#9]
In testing my ClojureScript in node, if one of my functions is not returning the correct thing orchestra will throw an error. Unfortunately, in that error the spec will be displayed as: `#object[cljs.spec.alpha.t_cljs$spec$alpha40677]` instead of the real spec key. This only happens for return values, input values are properly shown so I assume it's got something to do with orchestra.

**Comment by jeaye** [comment]
Hey, thanks for reporting this. I'm curious, what was your return spec? Do you get the same behavior when using keywords as the return spec?

**Comment by vikeri** [comment]
Sorry but I can't remember what I had as return value. I should have made a minimal repro case for you to test on. Now it's pretty hard for you to debug this.

**Comment by jeaye** [comment]
Well, I should've asked much sooner. :) No problem, I'll look deeper into this when I get a chance. Thanks again for the report.

**Comment by jeaye** [comment]
I've never seen something like this and nobody else has reported it. If this comes back up, feel free to let me know here and we can reopen the ticket. Thanks for using Orchestra!
